const fishingData = {
  "al": {
    name: "Alabama",
    status: "Legal with license",
    summary: "Requires a license for most anglers; diverse freshwater and saltwater fishing.",
    legalDetails: "Resident & non-resident licenses available. Specific regulations for bass, crappie, catfish, and saltwater species like redfish.",
  },
  "ak": {
    name: "Alaska",
    status: "Legal with license",
    summary: "World-class fishing with strict conservation rules. Licenses are required, and many areas have special regulations.",
    legalDetails: "Resident & non-resident licenses. King salmon require a stamp. Many areas have bait restrictions and gear-specific rules.",
  },
  "az": {
    name: "Arizona",
    status: "Legal with license",
    summary: "Fishing is permitted in lakes, rivers, and streams. A license is required for anglers 10 and older.",
    legalDetails: "Strong focus on trout and warm-water species like bass. Special regulations on urban lakes. Check for trout stamps.",
  },
  "ar": {
    name: "Arkansas",
    status: "Legal with license",
    summary: "Known as The Natural State, it offers extensive fishing opportunities. A license is required.",
    legalDetails: "Regulations for famous trout fisheries on the White River. Specific catfish and bass rules.",
  },
  "ca": {
    name: "California",
    status: "Legal with license",
    summary: "Requires a fishing license for anglers 16 and older. Both freshwater and saltwater (ocean) fishing are popular.",
    legalDetails: "Separate validations often needed for ocean fishing and second rod. Strict size and bag limits for species like bass and salmon.",
  },
  "co": {
    name: "Colorado",
    status: "Legal with license",
    summary: "Fishing is popular in mountain streams and reservoirs. All anglers 16 and older need a license.",
    legalDetails: "Habitat Stamp is required for first-time license buyers. Artificial flies and lures only on many streams.",
  },
  "ct": {
    name: "Connecticut",
    status: "Legal with license",
    summary: "A license is required for freshwater fishing. The state has a trout and salmon stamp.",
    legalDetails: "Separate marine fishing license is required for saltwater fishing. Specific seasons for trout.",
  },
  "de": {
    name: "Delaware",
    status: "Legal with license",
    summary: "Requires a license for freshwater fishing. A separate permit is needed for trout.",
    legalDetails: "No license required for saltwater fishing in Delaware's waters, but registration may be needed.",
  },
  "fl": {
    name: "Florida",
    status: "Legal with license",
    summary: "Famous for its freshwater and saltwater fishing. Licenses are required for both, with many exceptions.",
    legalDetails: "Saltwater license required unless fishing from a pier or for a specific species. Strict rules on snook, redfish, and tarpon.",
  },
  "ga": {
    name: "Georgia",
    status: "Legal with license",
    summary: "Requires a fishing license for most anglers. Offers both freshwater and saltwater fishing.",
    legalDetails: "Trout license required for certain streams. Free fishing days are offered.",
  },
  "hi": {
    name: "Hawaii",
    status: "Legal (mostly)",
    summary: "No license is required for saltwater recreational fishing from the shore or a private boat.",
    legalDetails: "A license is required for freshwater fishing. Many species have size and bag limits. Certain areas are closed for conservation.",
  },
  "id": {
    name: "Idaho",
    status: "Legal with license",
    summary: "A license is required for all anglers 14 and older. Renowned for trout and salmon fishing.",
    legalDetails: "Two-pole permit available. Some waters have special rules like barbless hooks only.",
  },
  "il": {
    name: "Illinois",
    status: "Legal with license",
    summary: "Requires a fishing license for residents and non-residents. Offers fishing in the Great Lakes and inland waters.",
    legalDetails: "Salmon stamp required for certain species. Specific regulations for the Illinois River.",
  },
  "in": {
    name: "Indiana",
    status: "Legal with license",
    summary: "A license is required for residents and non-residents. trout/salmon stamp is needed for those species.",
    legalDetails: "Free fishing days are offered. Specific regulations for Lake Michigan.",
  },
  "ia": {
    name: "Iowa",
    status: "Legal with license",
    summary: "Requires a license for anglers 16 and older. Good for trout, catfish, and panfish.",
    legalDetails: "Trout fee required to fish for trout or in designated trout streams.",
  },
  "ks": {
    name: "Kansas",
    status: "Legal with license",
    summary: "A license is required for anglers 16 and older. Offers reservoir and lake fishing.",
    legalDetails: "Some community fisheries require a permit. Regulations for paddlefish and sturgeon.",
  },
  "ky": {
    name: "Kentucky",
    status: "Legal with license",
    summary: "Requires a license for residents and non-residents. Known for bass and catfish fishing.",
    legalDetails: "Trout permit required if fishing for trout. Specific regulations for Ohio River boundary waters.",
  },
  "la": {
    name: "Louisiana",
    status: "Legal with license",
    summary: "Requires basic and saltwater licenses for most fishing. A legendary spot for bass and saltwater species.",
    legalDetails: "Special charter licenses available. Exceptions for fishing from a licensed charter.",
  },
  "me": {
    name: "Maine",
    status: "Legal with license",
    summary: "Requires a license for all anglers 16 and older. Famous for its wild brook trout and landlocked salmon.",
    legalDetails: "Separate salmon permit may be required. Ice fishing has its own specific regulations.",
  },
  "md": {
    name: "Maryland",
    status: "Legal with license",
    summary: "Requires a license for freshwater fishing and a separate registration for Chesapeake Bay and Atlantic coast fishing.",
    legalDetails: "Trout stamp required. Free fishing days available.",
  },
  "ma": {
    name: "Massachusetts",
    status: "Legal with license",
    summary: "Requires a license for freshwater fishing. A separate permit is needed for saltwater fishing.",
    legalDetails: "Trout stamp required. Specific regulations for striped bass in saltwater.",
  },
  "mi": {
    name: "Michigan",
    status: "Legal with license",
    summary: "Requires a license for all anglers 17 and older. Offers world-class Great Lakes and inland fishing.",
    legalDetails: "Two-pole license available. Separate stamp for trout/salmon. Alligator gar is strictly prohibited.",
  },
  "mn": {
    name: "Minnesota",
    status: "Legal with license",
    summary: "Known as The Land of 10,000 Lakes, it requires a license for anglers 16 and older.",
    legalDetails: "Trout and salmon stamp required for inland streams and Lake Superior. Dark house spearing requires a separate license.",
  },
  "ms": {
    name: "Mississippi",
    status: "Legal with license",
    summary: "Requires a license for residents and non-residents. Offers freshwater river and reservoir fishing.",
    legalDetails: "Saltwater license required for fishing in marine waters.",
  },
  "mo": {
    name: "Missouri",
    status: "Legal with license",
    summary: "Requires a license for residents and non-residents 16 and older. Renowned for trout parks.",
    legalDetails: "Trout permit required. Specific daily tags for trout in designated areas.",
  },
  "mt": {
    name: "Montana",
    status: "Legal with license",
    summary: "Requires a license for all anglers 12 and older. A world-class destination for trout fishing.",
    legalDetails: "Conservation license required before buying a fishing license. Strict catch-and-release and fly-fishing-only waters.",
  },
  "ne": {
    name: "Nebraska",
    status: "Legal with license",
    summary: "Requires a license for anglers 16 and older. Offers fishing in reservoirs and rivers.",
    legalDetails: "Habitat stamp required. Specific regulations for paddlefish.",
  },
  "nv": {
    name: "Nevada",
    status: "Legal with license",
    summary: "Requires a license for anglers 12 and older. Focuses on reservoir fishing for trout and bass.",
    legalDetails: "Second rod permit available. Special regulations for Lake Mead and Lake Tahoe.",
  },
  "nh": {
    name: "New Hampshire",
    status: "Legal with license",
    summary: "Requires a license for anglers 16 and older. Offers lakes and coastal fishing.",
    legalDetails: "Separate license required for saltwater fishing. Trout and salmon permit needed.",
  },
  "nj": {
    name: "New Jersey",
    status: "Legal with license",
    summary: "Requires a license for freshwater fishing and a separate registry for saltwater fishing.",
    legalDetails: "Trout stamp required. Highly specific regulations for striped bass.",
  },
  "nm": {
    name: "New Mexico",
    status: "Legal with license",
    summary: "Requires a license for anglers 12 and older. Focus on high-altitude trout lakes and rivers.",
    legalDetails: "Second rod validation available. Special rules for quality-waters and catch-and-release areas.",
  },
  "ny": {
    name: "New York",
    status: "Legal with license",
    summary: "Requires a license for anglers 16 and older. Offers diverse fishing from the Great Lakes to mountain streams.",
    legalDetails: "Marine fishing registry required for saltwater species. FREE Fishing Days are scheduled.",
  },
  "nc": {
    name: "North Carolina",
    status: "Legal with license",
    summary: "Requires a license for inland (freshwater) fishing. A separate license is needed for coastal waters.",
    legalDetails: "Trout license required for certain waters. Unified license options available.",
  },
  "nd": {
    name: "North Dakota",
    status: "Legal with license",
    summary: "Requires a license for anglers 16 and older. Focus on walleye and pike in prairie lakes.",
    legalDetails: "General license includes salmonid fishing.",
  },
  "oh": {
    name: "Ohio",
    status: "Legal with license",
    summary: "Requires a license for residents and non-residents 16 and older. Offers Lake Erie and inland fishing.",
    legalDetails: "Trout and salmon stamp may be required. One-day licenses are available.",
  },
  "ok": {
    name: "Oklahoma",
    status: "Legal with license",
    summary: "Requires a license for residents and non-residents 16 and older.",
    legalDetails: "License includes trout fishing. Separate license required for fishing in the Red River.",
  },
  "or": {
    name: "Oregon",
    status: "Legal with license",
    summary: "Requires a license for all anglers 12 and older. Offers Pacific Ocean, river, and lake fishing.",
    legalDetails: "Combined Angling Tag required for salmon, steelhead, sturgeon, and halibut. Columbia River Basin Endorsement required.",
  },
  "pa": {
    name: "Pennsylvania",
    status: "Legal with license",
    summary: "Requires a license for anglers 16 and older. A trout and salmon permit is also required.",
    legalDetails: "Lake Erie permit required. Special regulations on approved trout waters.",
  },
  "ri": {
    name: "Rhode Island",
    status: "Legal with license",
    summary: "Requires a license for freshwater fishing. A separate license is needed for saltwater fishing.",
    legalDetails: "Trout conservation stamp required.",
  },
  "sc": {
    name: "South Carolina",
    status: "Legal with license",
    summary: "Requires a license for freshwater fishing. A separate license is needed for saltwater fishing.",
    legalDetails: "Combination licenses available. Specific rules for shad and herring.",
  },
  "sd": {
    name: "South Dakota",
    status: "Legal with license",
    summary: "Requires a license for residents and non-residents 16 and older. Known for walleye and trout.",
    legalDetails: "License includes salmonid fishing. Specific permits for certain waters like the Missouri River.",
  },
  "tn": {
    name: "Tennessee",
    status: "Legal with license",
    summary: "Requires a license for residents and non-residents 13 and older.",
    legalDetails: "Type 066 license (trout) is an add-on for specific species. Free fishing days available.",
  },
  "tx": {
    name: "Texas",
    status: "Legal with license",
    summary: "Requires a license for freshwater fishing. A saltwater license is needed for fishing in the Gulf.",
    legalDetails: "Alligator gar fishing is legal but highly regulated with a tag system. Free fishing days offered.",
  },
  "ut": {
    name: "Utah",
    status: "Legal with license",
    summary: "Requires a license for anglers 12 and older. Offers fishing in reservoirs and high-mountain lakes.",
    legalDetails: "Second-pole permit available. Dedicated catch-and-release fisheries.",
  },
  "vt": {
    name: "Vermont",
    status: "Legal with license",
    summary: "Requires a license for anglers 15 and older.",
    legalDetails: "Trout and salmon permit required. Lake trout and salmon stamp may be needed.",
  },
  "va": {
    name: "Virginia",
    status: "Legal with license",
    summary: "Requires a license for freshwater fishing. A separate license is needed for saltwater fishing.",
    legalDetails: "Trout license required. License-free fishing days available.",
  },
  "wa": {
    name: "Washington",
    status: "Legal with license",
    summary: "Requires a license for anglers 15 and older. Offers Pacific Ocean, Puget Sound, and freshwater fishing.",
    legalDetails: "Endorsements required for salmon, steelhead, sturgeon, and crab. Columbia River Basin endorsement required.",
  },
  "wv": {
    name: "West Virginia",
    status: "Legal with license",
    summary: "Requires a license for residents and non-residents.",
    legalDetails: "Trout stamp required. Free fishing days available.",
  },
  "wi": {
    name: "Wisconsin",
    status: "Legal with license",
    summary: "Requires a license for anglers 16 and older. Offers Great Lakes and inland fishing.",
    legalDetails: "Trout and salmon stamp required. Inland and Great Lakes trout stamps are separate.",
  },
  "wy": {
    name: "Wyoming",
    status: "Legal with license",
    summary: "Requires a license for anglers 14 and older. A world-class destination for trout fishing.",
    legalDetails: "Conservation stamp required. Specific regulations for native cutthroat trout.",
  }
};