const huntingData = {
    "al": {
        name: "Alabama",
        status: "Legal with license",
        summary: "Diverse game including deer, turkey, and alligator.",
        legalDetails: "Hunter Ed required for those born after 1977. Alligator hunting requires a separate lottery permit.",
    },
    "ak": {
        name: "Alaska",
        status: "Legal with license",
        summary: "World-class hunting for moose, caribou, and bear; heavily regulated.",
        legalDetails: "Hunter Ed required for those born after 1986. Non-residents typically need a guide for big game.",
    },
    "az": {
        name: "Arizona",
        status: "Legal with license",
        summary: "Renowned for trophy elk and sheep; mostly draw-only for big game.",
        legalDetails: "Uses a bonus point system for draw permits. Hunter Ed required for those born after 1966.",
    },
    "ar": {
        name: "Arkansas",
        status: "Legal with license",
        summary: "Abundant deer, turkey, and unique elk and alligator opportunities.",
        legalDetails: "Hunter Ed required for those 16+ born after 1968. Alligator hunting is by permit only.",
    },
    "ca": {
        name: "California",
        status: "Legal with license",
        summary: "Varied game but with strict firearm and ammunition laws.",
        legalDetails: "Non-lead ammunition is required for all hunting. Hunter Ed is mandatory for first-time buyers.",
    },
    "co": {
        name: "Colorado",
        status: "Legal with license",
        summary: "Premier destination for elk and mule deer on vast public lands.",
        legalDetails: "Mix of over-the-counter and draw tags. Hunter Ed required for those born after 1949.",
    },
    "ct": {
        name: "Connecticut",
        status: "Legal with license",
        summary: "Regulated hunting for deer and turkey in a dense population state.",
        legalDetails: "Written permission required for private land. Sunday hunting is prohibited on public land.",
    },
    "de": {
        name: "Delaware",
        status: "Legal with license",
        summary: "Popular waterfowl and deer hunting, primarily on private farmland.",
        legalDetails: "A state waterfowl stamp is required in addition to the federal stamp.",
    },
    "fl": {
        name: "Florida",
        status: "Legal with license",
        summary: "Unique game like deer, hog, and alligator across diverse habitats.",
        legalDetails: "Alligator hunting is managed through a lottery permit system. Extensive WMA rules apply.",
    },
    "ga": {
        name: "Georgia",
        status: "Legal with license",
        summary: "Abundant deer, turkey, and bear with long seasons and generous bags.",
        legalDetails: "Baiting is legal. A Big Game License is required for deer, bear, and turkey.",
    },
    "hi": {
        name: "Hawaii",
        status: "Legal with license",
        summary: "Hunting for introduced game like axis deer, pig, and sheep.",
        legalDetails: "Most hunting is on private land leases. Regulations vary significantly by island.",
    },
    "id": {
        name: "Idaho",
        status: "Legal with license",
        summary: "Vast public land hunting for elk, deer, and wolf.",
        legalDetails: "Many tags available over-the-counter. Wolf hunting requires a separate tag.",
    },
    "il": {
        name: "Illinois",
        status: "Legal with license",
        summary: "Known for trophy whitetail deer, primarily on private land.",
        legalDetails: "Firearm deer seasons are mostly permit-based through a lottery. Non-resident permits are limited.",
    },
    "in": {
        name: "Indiana",
        status: "Legal with license",
        summary: "Strong white-tailed deer and turkey hunting on mixed land.",
        legalDetails: "Deer hunting requires a license and a deer license bundle for tags.",
    },
    "ia": {
        name: "Iowa",
        status: "Legal with license",
        summary: "Premier trophy deer state with limited non-resident tags.",
        legalDetails: "Non-resident deer tags are allocated through a highly competitive lottery system.",
    },
    "ks": {
        name: "Kansas",
        status: "Legal with license",
        summary: "Top-tier for trophy whitetail, turkey, pheasant, and quail.",
        legalDetails: "Non-resident deer tags are available through a draw system with preference points.",
    },
    "ky": {
        name: "Kentucky",
        status: "Legal with license",
        summary: "High deer population and coveted elk hunting through a draw.",
        legalDetails: "Elk tags are highly coveted through a lottery. Hunter Ed mandatory for those born after 1975.",
    },
    "la": {
        name: "Louisiana",
        status: "Legal with license",
        summary: "Diverse hunting for deer, waterfowl, alligator, and wild hog.",
        legalDetails: "Alligator hunting requires a separate permit obtained through a lottery.",
    },
    "me": {
        name: "Maine",
        status: "Legal with license",
        summary: "Remote hunting for moose (by draw), white-tailed deer, and black bear.",
        legalDetails: "Moose permits are allocated through a lottery system that favors residents.",
    },
    "md": {
        name: "Maryland",
        status: "Legal with license",
        summary: "Hunting for deer, bear, waterfowl, and turkey with urban archery seasons.",
        legalDetails: "Sunday hunting is permitted on private land and certain public lands.",
    },
    "ma": {
        name: "Massachusetts",
        status: "Legal with license",
        summary: "Regulated hunting for deer and turkey in a high-density state.",
        legalDetails: "All hunting requires written permission on private land. Sunday hunting is prohibited.",
    },
    "mi": {
        name: "Michigan",
        status: "Legal with license",
        summary: "Renowned for whitetail deer, black bear, and waterfowl.",
        legalDetails: "Bear and elk hunting are limited to a draw system. Separate licenses required.",
    },
    "mn": {
        name: "Minnesota",
        status: "Legal with license",
        summary: "Famous for whitetail deer and waterfowl; offers moose hunting (lottery).",
        legalDetails: "Firearm deer seasons are split into several 'A' and 'B' seasons by zone.",
    },
    "ms": {
        name: "Mississippi",
        status: "Legal with license",
        summary: "Long seasons for deer and turkey with liberal bag limits.",
        legalDetails: "Baiting is legal. A WMA permit is required for hunting on state management areas.",
    },
    "mo": {
        name: "Missouri",
        status: "Legal with license",
        summary: "Excellent whitetail and turkey hunting; offers a limited elk season (by draw).",
        legalDetails: "The 'Alternative Methods' season includes crossbows, atlatls, and pistols.",
    },
    "mt": {
        name: "Montana",
        status: "Legal with license",
        summary: "Iconic big game hunting for elk, mule deer, antelope, and more.",
        legalDetails: "Uses a drawing with a preference point system for non-resident tags.",
    },
    "ne": {
        name: "Nebraska",
        status: "Legal with license",
        summary: "Great plains hunting for deer, turkey, and prairie antelope.",
        legalDetails: "Extensive public access through the Walk-In Access program on private land.",
    },
    "nv": {
        name: "Nevada",
        status: "Legal with license",
        summary: "Known for trophy mule deer and sheep; almost entirely a draw-only state.",
        legalDetails: "Uses a bonus point system for draws. Non-resident tags are very limited.",
    },
    "nh": {
        name: "New Hampshire",
        status: "Legal with license",
        summary: "Hunting for deer, bear, moose (by lottery), and turkey.",
        legalDetails: "Moose permits are highly sought after in an annual lottery.",
    },
    "nj": {
        name: "New Jersey",
        status: "Legal with license",
        summary: "Heavily regulated hunting with strong deer management programs.",
        legalDetails: "Has some of the nation's strictest firearm laws. Bear seasons are not always available.",
    },
    "nm": {
        name: "New Mexico",
        status: "Legal with license",
        summary: "Premier draw-only state for trophy elk, deer, oryx, and ibex.",
        legalDetails: "Non-residents must apply through a complex draw; many hunts require a guide.",
    },
    "ny": {
        name: "New York",
        status: "Legal with license",
        summary: "Significant whitetail deer and black bear hunting in large regions.",
        legalDetails: "State is divided into WMUs with specific season dates and regulations.",
    },
    "nc": {
        name: "North Carolina",
        status: "Legal with license",
        summary: "Diverse hunting from coastal waterfowl to mountain bear and deer.",
        legalDetails: "Bear hunting often requires the use of dogs in eastern counties.",
    },
    "nd": {
        name: "North Dakota",
        status: "Legal with license",
        summary: "Legendary waterfowl hunting and strong deer and pheasant populations.",
        legalDetails: "Non-resident deer and waterfowl licenses are limited and allocated by lottery.",
    },
    "oh": {
        name: "Ohio",
        status: "Legal with license",
        summary: "High deer population with archery, gun, and muzzleloader seasons.",
        legalDetails: "Hunting is primarily on private land. An antlerless permit is required in certain seasons.",
    },
    "ok": {
        name: "Oklahoma",
        status: "Legal with license",
        summary: "Offers hunting for deer, turkey, and limited elk (in specific areas).",
        legalDetails: "Elk hunting is primarily limited to the Wichita Mountains Refuge and requires a draw.",
    },
    "or": {
        name: "Oregon",
        status: "Legal with license",
        summary: "Diverse hunting for elk, deer, and bear; mostly controlled hunts (draw).",
        legalDetails: "Uses a tag system for specific species and weapons. Non-resident tags are limited.",
    },
    "pa": {
        name: "Pennsylvania",
        status: "Legal with license",
        summary: "Huge tradition of whitetail deer and turkey hunting with high hunter density.",
        legalDetails: "A unique flintlock muzzleloader season occurs after Christmas.",
    },
    "ri": {
        name: "Rhode Island",
        status: "Legal with license",
        summary: "Limited hunting for deer and turkey due to the state's small size.",
        legalDetails: "Hunting on private land requires written permission. Zones have quotas for deer.",
    },
    "sc": {
        name: "South Carolina",
        status: "Legal with license",
        summary: "Long seasons and liberal bag limits for deer and alligator.",
        legalDetails: "Baiting for deer is legal. Alligator hunting is managed through a lottery permit system.",
    },
    "sd": {
        name: "South Dakota",
        status: "Legal with license",
        summary: "World-famous pheasant hunting. Also offers deer and antelope.",
        legalDetails: "Non-resident pheasant licenses are limited and sell out quickly.",
    },
    "tn": {
        name: "Tennessee",
        status: "Legal with license",
        summary: "High white-tailed deer population and limited elk hunt by draw.",
        legalDetails: "A Type 094 permit is required for turkey. Elk tags are highly coveted draw tags.",
    },
    "tx": {
        name: "Texas",
        status: "Legal with license",
        summary: "Mostly on private land via leases or paid hunts for deer, exotics, and hog.",
        legalDetails: "No state bag limit on feral hogs. A mandatory tagging system is used for deer and turkey.",
    },
    "ut": {
        name: "Utah",
        status: "Legal with license",
        summary: "Known for trophy mule deer and elk; bonus point draw system for big game.",
        legalDetails: "Nearly all big game hunting is managed through a limited entry draw system.",
    },
    "vt": {
        name: "Vermont",
        status: "Legal with license",
        summary: "Hunting for white-tailed deer, black bear, and moose (by lottery).",
        legalDetails: "Moose permits are allocated through a lottery. Bear hunting can involve hounds.",
    },
    "va": {
        name: "Virginia",
        status: "Legal with license",
        summary: "Strong traditions of deer, bear, and turkey hunting across diverse geography.",
        legalDetails: "Sunday hunting is permitted on private land with permission.",
    },
    "wa": {
        name: "Washington",
        status: "Legal with license",
        summary: "Offers elk, deer, bear, and cougar hunting in defined management units.",
        legalDetails: "Many hunts are draw-only for quality tags. A special cougar tag is required.",
    },
    "wv": {
        name: "West Virginia",
        status: "Legal with license",
        summary: "Mountainous terrain provides hunting for deer, bear, and turkey.",
        legalDetails: "Bear hunting seasons are long and involve multiple methods (with dogs, etc.).",
    },
    "wi": {
        name: "Wisconsin",
        status: "Legal with license",
        summary: "Legendary white-tailed deer hunting and draw-based bear hunting.",
        legalDetails: "Bear tags are allocated through a preference point draw system due to high demand.",
    },
    "wy": {
        name: "Wyoming",
        status: "Legal with license",
        summary: "Iconic hunting for elk, mule deer, pronghorn, and species like bison.",
        legalDetails: "A mix of general license areas and limited quota draw areas for non-residents.",
    },
};